openapi: 3.0.1
info:
  title: Tender CRM - Tender Management Entity Model
  description: API для сервиса отправки извещений
  version: 0.0.1-SNAPSHOT
paths:
  /:
    get:
      tags:
        - default controller
      responses:
        "400":
          description: Ошибка обработки запроса
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        "500":
          description: Ошибка работы сервера
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        "200":
          description: Запрос обработан успешно

components:
  schemas:
    ErrorResponse:
      required:
        - code
        - message
      type: object
      properties:
        code:
          maxLength: 32
          type: string
          description: Код ошибки
          example: BAD_REQUEST
        message:
          maxLength: 256
          type: string
          description: Описание ошибки
          example: Validation exception occurred
    TenderData:
      type: object
      properties:
        tenderNmcCost:
          type: double
          description: Стоимость тендера NMC
        tenderCost:
          type: double
          description: Стоимость тендера

    AttachmentDto:
      required:
        - contentMap
        - templateCode
      type: object
      properties:
        templateCode:
          maxLength: 64
          type: string
          description: Код шаблона вложения
          example: QUALIFICATION
        contentMap:
          maxItems: 100
          minItems: 1
          type: array
          description: Список параметров вложения
          items:
            $ref: '#/components/schemas/ContentMapDto'
      description: Список вложений письма
    ContentMapDto:
      required:
        - paramName
        - paramValue
      type: object
      properties:
        paramName:
          maxLength: 32
          type: string
          description: Ключ параметра
          example: full_name
        paramValue:
          maxLength: 512
          type: string
          description: Значение параметра
          example: Иванов Иван Иванович
      description: Список параметров вложения
    NotificationBodyDto:
      required:
        - contentMap
      type: object
      properties:
        contentMap:
          maxItems: 100
          type: array
          description: Список параметров тела письма
          items:
            $ref: '#/components/schemas/ContentMapDto'
      description: Блок для параметров тела письма